service: sending-messages-CognitoUserPool

frameworkVersion: "3.28.1"

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  environment:
    WEBSITE_BASE_DOMAIN_NAME: "https://alexserverlesssystem-codedeployment-main-dev.s3.us-west-2.amazonaws.com"
  name: aws
  region: "us-west-2"
  stage: "dev"

  deploymentBucket:
    name: sending-messages-codedeployment-bucket-${self:custom.stage}

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
            Mutable: false
          - Name: name
            Required: true
            Mutable: false
        UserPoolName: sending-messages-CognitoUserPool
    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: "2345678"
        UserPoolId: !Ref CognitoUserPool
      DependsOn: CognitoUserPool

  Outputs:
    CognitoUserPoolId:
      Description: "Cognito user pool id"
      Value: !Ref CognitoUserPool
      Export:
        Name: sending-messages-CognitoUserPoolId
    CognitoUserPoolArn:
      Description: "Cognito user pool arn"
      Value: !GetAtt [CognitoUserPool, Arn]
      Export:
        Name: sending-messages-CognitoUserPoolArn